/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CurveStethPool,
  CurveStethPoolInterface,
} from "../CurveStethPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_token_amount",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "i",
        type: "int128",
      },
    ],
    name: "calc_withdraw_one_coin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CurveStethPool__factory {
  static readonly abi = _abi;
  static createInterface(): CurveStethPoolInterface {
    return new utils.Interface(_abi) as CurveStethPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurveStethPool {
    return new Contract(address, _abi, signerOrProvider) as CurveStethPool;
  }
}
